### ISSUE TITLE
Cannot run in development mode

### ISSUE THREAD

**Issue by patrick99e99** [lionsharecapital/lionshare-desktop#89]
When following the provided instructions, I get:

	>yarn run dev
	yarn run v0.27.5
	$ concurrently -k 'node desktop/server.dev.js' 'npm start'
	[1] module.js:487
	[1]     throw err;
	[1]     ^
	[1]
	[1] Error: Cannot find module 'update-notifier'
	[1]     at Function.Module._resolveFilename (module.js:485:15)
	[1]     at Function.Module._load (module.js:437:25)
	[1]     at Module.require (module.js:513:17)
	[1]     at require (internal/module.js:11:18)
	[1]     at /usr/local/lib/node_modules/npm/bin/npm-cli.js:29:19
	[1]     at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
	[1]     at Module._compile (module.js:569:30)
	[1]     at Object.Module._extensions..js (module.js:580:10)
	[1]     at Module.load (module.js:503:32)
	[1]     at tryModuleLoad (module.js:466:12)
	[1] npm start exited with code 1
	[0] listening on 3000
	--> Sending SIGTERM to other processes..
	[0] node desktop/server.dev.js exited with code null
	error Command failed with exit code 1.
	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Running yarn actually broke node on my system completely, any attempt to use it would result in that same error.  I actually had to remove ~/.npm, and /usr/local/lib/node_modules, then uninstall node and reinstall it, in order to get my system running.

If you could please provide me with any information on how I can actually build this project, I would greatly appreciate it.

**Comment by dgoncalves81** [comment]
Having the same issue as well - maybe an issue with yarn and the most recent versions of OSX.

If anyone has any advice on how to get a build up and running it would be greatly appreciated - or if anyone can release a new binary build with the new changes

**Comment by diogopms** [comment]
Hey @dgoncalves81, I didn't have any issue running the dev mode, expect changing the 
`prettier` in `package.json`.

```js
     "node-sass": "^3.4.2",
     "node-static": "^0.7.7",
     "pre-commit": "^1.2.2",
-    "prettier": "git+ssh://git@github.com/prettier/prettier.git",
+    "prettier": "^1.5.0",
     "rebass": "^0.2.6",
     "resolve-url": "^0.2.1",
     "resolve-url-loader": "^1.4.3",
```

**Comment by zachdunn** [comment]
Had a similar issue, and ended up just using `npm install` with `npm run dev` without issue. I suspect the latest `yarn` is to blame here.

**Comment by bediaz** [comment]
In package.json, I had to change `git+ssh` to `git+https` in order to get yarn to run properly on my machine.

**Comment by jenbennings** [comment]
Apologies for this, will investigate over the next week or so when I get a chance.

**Comment by ispyhumanfly** [comment]
This is resolved in the fork I'm working on. https://thoughtpivot.com/lionshare-desktop
